### ISSUE TITLE
proot.me no longer resolves

### ISSUE THREAD

**Issue by ocharles** [proot-me/PRoot#118] opened 2017-02-27 10:17 UTC

**Comment by gbraad** [comment] 2017-03-09 16:35
You can find downloads at: https://github.com/proot-me/proot-static-build/releases

**Comment by jopasserat** [comment] 2017-03-09 16:52
the new website is hosted at https://proot-me.github.io/
closed as duplicate of #113
please open PR if you find occurrences of the old URL in the code

**Closed by jopasserat** 2017-03-09 16:52 UTC

**Comment by hugobuddel** [comment] 2018-07-03 08:30
Also, those binaries seem quite old, like from 2016, are the binaries not built anymore?
https://github.com/proot-me/proot-static-build/issues/5
