### ISSUE TITLE
terminated with signal 11

### ISSUE THREAD

**Issue by IceflowRE** [proot-me/PRoot#112] opened 2017-01-06 20:48 UTC
I tried to proot on `4.8.13-1-ARCH` to an `arm/ Debian` (server image: https://www.armbian.com/odroid-c2/).

(The boot is an extra partition but was mounted correctly to the boot folder)

I used proot `5.1.0` with `built-in accelerators: process_vm = yes, seccomp_filter = yes`

The result was:
```
[iceflower@Pc 49bbcbb8-56e7-4bfd-b691-05fde5471c05]$ proot -v 10 -R . -q qemu-arm-static -0
proot info: binding = /dev/null:/etc/ld.so.preload
proot info: binding = /:/host-rootfs
proot info: binding = /run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05
proot info: binding = /home/iceflower
proot info: binding = /run/dbus/system_bus_socket
proot info: binding = /run
proot info: binding = /tmp
proot info: binding = /sys
proot info: binding = /dev
proot info: binding = /usr/share/zoneinfo/Europe/Berlin:/etc/localtime
proot info: binding = /etc/resolv.conf
proot info: binding = /etc/nsswitch.conf
proot info: binding = /etc/group
proot info: binding = /etc/passwd
proot info: binding = /proc/1141/mounts:/proc/mounts
proot info: binding = /proc
proot info: binding = /etc/hosts
proot info: binding = /etc/host.conf
proot info: binding = /run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05:/
proot info: pid 1141: translate("/" + "/bin/sh")
proot info: pid 1141:          -> "/run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05/bin/dash"
proot info: pid 1141: translate("/" + "/bin/sh")
proot info: pid 1141:          -> "/run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05/bin/sh"
proot info: host rootfs = /host-rootfs
proot info: glue rootfs = /tmp/proot-1141-mSo5tP
proot info: exe = /bin/sh
proot info: argv =
proot info: qemu = /usr/bin/qemu-arm-static
proot info: initial cwd = /run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05
proot info: verbose level = 10
proot info: pid 1141: access to "/dev/pts/1" (fd 0) won't be translated until closed
proot info: pid 1141: access to "/dev/pts/1" (fd 1) won't be translated until closed
proot info: pid 1141: access to "/dev/pts/1" (fd 2) won't be translated until closed
proot info: pid 1141: access to "/proc/1141/fd" (fd 3) won't be translated until closed
proot info: pid 1142: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb4506828, 0]
proot info: pid 1142: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb4506828, 0]
proot info: pid 1142: sysexit start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf11e0630) = 0x0 [0x7ffeb4506828, 0]
proot info: pid 1142: sysexit end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf11e0630) = 0x0 [0x7ffeb4506828, 0]
proot info: pid 1142: sysenter start: prctl(0x16, 0x2, 0x7ffeb4506870, 0x7fc26591e01a, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb4506828, 0]
proot info: pid 1142: sysenter end: prctl(0x16, 0x2, 0x7ffeb4506870, 0x7fc26591e01a, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb4506828, 0]
proot info: pid 1142: sysexit start: prctl(0x16, 0x2, 0x7ffeb4506870, 0x7fc26591e01a, 0x0, 0xf11e0630) = 0x0 [0x7ffeb4506828, 0]
proot info: pid 1142: sysexit end: prctl(0x16, 0x2, 0x7ffeb4506870, 0x7fc26591e01a, 0x0, 0xf11e0630) = 0x0 [0x7ffeb4506828, 0]
proot info: pid 1142: sysenter start: execve(0x2125310, 0x7ffeb4506930, 0x7ffeb4506b10, 0x5b5, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb45068a8, 0]
proot info: pid 1142: translate("/" + "/bin/sh")
proot info: pid 1142:          -> "/run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05/bin/dash"
proot info: loader: /tmp/prooted-1141-qYsw1n
proot info: pid 1142: sysenter end: execve(0x7ffeb4505f91, 0x7ffeb45067b5, 0x7ffeb4505faa, 0x5b5, 0x0, 0xf11e0630) = 0xffffffffffffffda [0x7ffeb4505f91, 0]
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: pid 1142: translate("/" + "/bin/sh")
proot info: pid 1142:          -> "/run/media/iceflower/49bbcbb8-56e7-4bfd-b691-05fde5471c05/bin/sh"
proot info: pid 1142: terminated with signal 11

```

**Comment by jopasserat** [comment] 2017-01-07 14:46
closed as duplicate of #106

**Closed by jopasserat** 2017-01-07 14:46 UTC
