### ISSUE TITLE
chgrp does not work with the -0 option

### ISSUE THREAD

**Issue by dlech** [proot-me/PRoot#92] opened 2015-09-20 20:18 UTC
I can see at https://github.com/proot-me/PRoot/blob/f393b4daf9bfd6d034cf2c8dd56d44f135b08e93/src/extension/fake_id0/fake_id0.c#L299, this is not implemented.

Any advice on how to implement this or work around it?

**Comment by dlech** [comment] 2015-10-24 15:27
Same thing with `chown`.

**Comment by QiangF** [comment] 2016-11-30 13:21
When I log in as root, ls -la  show all files are owned by root, when I log in  as normal user, all files are shown to be owned by that user .

**Comment by 138bit** [comment] 2019-02-08 09:06
I think he's referring to the following:
[..]
chgrp: changing group of '/etc/ssl/private/ssl-cert-snakeoil.key': Permission denied
dpkg: error processing package ssl-cert (--configure):
 subprocess installed post-installation script returned error exit status 1
[..]

I have this error on the server at work, but not on my laptop. Both are running Debian Stretch. I too have problems with chown, but this can be "solved" with `fakeroot -- proot [..]`

INFO
Architecture: server & client = amd64, rootfs = armhf
kernel: server = 4.20.2 (custom), client = 4.19.0-0.bpo.1-amd64 (stretch-backports)
proot: 5.1.0 (server, client)
fakeroot: 1.21 (server, client)
passwd: 1:4.4-4.1 (server, client)

**Comment by oxr463** [comment] 2019-02-08 11:39
Thanks for the info! This sounds similar to https://github.com/proot-me/PRoot/issues/156.

**Comment by 138bit** [comment] 2019-02-08 12:44
You're welcome! 
I've implemented that workaround already, thus its not the same issue (I think). I will have to get a hold of the server its logs before I can send you additional information. Do you need other version numbers?

**Comment by oxr463** [comment] 2019-02-08 14:51
I think you have provided plenty of information. From the other issue (#156), we concluded that his issue was specific to Debian and kin; is it possible for you to try another distribution? Literally anything is fine, just not a derivative of Debian.

**Comment by 138bit** [comment] 2019-02-08 15:32
The strangest thing; the source is able to configure the root file system. Basically nothing has changed except some PRs are approved and merged to master. I was testing on a test branch which had the branches in question merged. Of course I cant reproduce the error any more because I've removed the test branch, sorry :/ 

I do have some time to retrace my steps this weekend and I hope it will shine some light on this mystery. If I find something I'll post it here. 

Furthermore, I suggest to close this issue, because it has been 3 years and nobody else has commented here since. You can always reopen it if somebody gets this error in 2021 ;-)

Thanks for your help.

**Comment by oxr463** [comment] 2019-02-08 15:50
Hmm, well that's good since I'm the one responsible for quite a few of those merges! 😉 

True, hopefully this doesn't come up again, but if it does we can reopen it.

You're welcome!

**Closed by oxr463** 2019-02-08 15:50 UTC
