### ISSUE TITLE
vpid 1: terminated with signal 7

### ISSUE THREAD

**Issue by basukon** [proot-me/proot#190] opened 2019-10-11 14:08 UTC
Im trying to use this proot version and also the termux proot fork inside the Linux On Dex environment (which is Samsungs environment to run Linux Desktops in android) to see if I can get better processes handling because triggers on apk alpinelinux or hooks on pacman archlinux aren't executing properly on the LinuxOnDesk chroot, so packages aren't executing pre/post instructions. So far I was able to package ArchLinux and AlpineLinux as custom images for LinuxOnDex which has accelerated vnc support which makes it really pleasant to use in contrast to regular vnc connection that feels laggy and slow, the LinuxOnDesk ubuntu image ships a custom Xtightvnc binary that provides the accelerated support by communicating with host Display.

I'm testing from an archlinux install inside LinuxOnDesk chroot and prooting into an alpinelinux root-fs with **proot -S alpine /bin/ash** and get both on termux proot and this repo proot the message: **vpid 1: terminated with signal 7**, with termux proot fork I get better debugging messages which follow below:

```
proot info: binding = /home/dextop/alpine
proot info: binding = /home/dextop
proot info: binding = /tmp
proot info: binding = /proc
proot info: binding = /sys
proot info: binding = /dev
proot info: binding = /etc/resolv.conf
proot info: binding = /etc/nsswitch.conf
proot info: binding = /etc/hosts
proot info: binding = /etc/host.conf
proot info: binding = /home/dextop/alpine:/
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/ash"
proot info: glue rootfs = /tmp/proot-19873-hlsnZm
proot info: exe = /bin/ash
proot info: argv = /bin/ash
proot info: initial cwd = /home/dextop
proot info: verbose level = 2
proot info: pid 19873: access to "/devro/pts/1" (fd 0) won't be translated until closed
proot info: pid 19873: access to "/home/dextop/out.txt" (fd 1) won't be translated until closed
proot info: pid 19873: access to "/home/dextop/out.txt" (fd 2) won't be translated until closed
proot info: pid 19873: access to "/proc/19873/fd" (fd 3) won't be translated until closed
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: translate("/" + "/lib/ld-musl-aarch64.so.1")
proot info: vpid 1:          -> "/home/dextop/alpine/lib/ld-musl-aarch64.so.1"
proot info: loader: /tmp/prooted-19873-E4Dqqz
proot info: ptrace acceleration (seccomp mode 2, new syscall order) enabled
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: translate("/" + "/lib/ld-musl-aarch64.so.1")
proot info: vpid 1:          -> "/home/dextop/alpine/lib/ld-musl-aarch64.so.1"
proot info: vpid 1: translate("/" + "/bin/busybox")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: terminated with signal 7
```
This [old static builds](https://github.com/proot-me/proot-static-build/tree/master/static) especially the proot-arm64 which is the one I'm using does works well (not sure if it has something to do with been statically compiled). The only issue with this old statically compiled binaries is that I get the same error of alpine not processing the busybox triggers which I think is fixed on newer proot code and does seem to work properly inside termux with pacman and apk properly processing the hooks/triggers, but this error message shows inside the LinuxOnDesk chroot... I also reported the issue to the termux proot fork https://github.com/termux/proot/issues/78 not sure how to reference it.

The advantage of LinuxOnDesk is that the accelerated vnc connection makes it feel like if you aren't using vnc at all, I'm even writing this report from ArchLinux XFCE desktop running inside LinuxOnDesk.

Just in case I also attached the [strace output](https://github.com/proot-me/proot/files/3717960/out.txt)

**Comment by oxr463** [comment] 2019-10-11 20:00
Duplicate of https://github.com/proot-me/proot/issues/180

**Comment by basukon** [comment] 2019-10-13 18:40
Just in case here is the verbose 9 output since I didn't noticed the -v flag:

```
proot info: binding = /home/dextop/alpine
proot info: binding = /home/dextop
proot info: binding = /tmp
proot info: binding = /proc
proot info: binding = /sys
proot info: binding = /dev
proot info: binding = /etc/resolv.conf
proot info: binding = /etc/nsswitch.conf
proot info: binding = /etc/hosts
proot info: binding = /etc/host.conf
proot info: binding = /home/dextop/alpine:/
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/ash"
proot info: glue rootfs = /tmp/proot-6758-haUMmz
proot info: exe = /bin/ash
proot info: argv = /bin/ash
proot info: initial cwd = /home/dextop
proot info: verbose level = 9
proot info: pid 6758: access to "/devro/pts/0" (fd 0) won't be translated until closed
proot info: pid 6758: access to "/home/dextop/proot.log" (fd 1) won't be translated until closed
proot info: pid 6758: access to "/home/dextop/proot.log" (fd 2) won't be translated until closed
proot info: pid 6758: access to "/proc/6758/fd" (fd 3) won't be translated until closed
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x96) = 0x26 [0x7fe95a8bd0, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x96) = 0x26 [0x7fe95a8bd0, 0]
proot info: vpid 1: sysexit start: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0x96) = 0x0 [0x7fe95a8bd0, 0]
proot info: vpid 1: sysexit end: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0x96) = 0x0 [0x7fe95a8bd0, 0]
proot info: vpid 1: sysenter start: execve(0x5b3b1c6f70, 0x7fe95a8ec0, 0x7fe95a8ed0, 0x20, 0x40100401, 0xaaaa0101aaaaaaaa) = 0x5b3b1c6f70 [0x7fe95a8bf0, 0]
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: translate("/" + "/lib/ld-musl-aarch64.so.1")
proot info: vpid 1:          -> "/home/dextop/alpine/lib/ld-musl-aarch64.so.1"
proot info: loader: /tmp/prooted-6758-GjuGSW
proot info: vpid 1: sysenter end: execve(0x7fe95a8bd7, 0x7fe95a8ec0, 0x7fe95a8ed0, 0x20, 0x40100401, 0xaaaa0101aaaaaaaa) = 0x7fe95a8bd7 [0x7fe95a8bd7, 0]
proot info: vpid 1: sysexit start: io_setup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0x7fff1b2450, 0]
proot info: vpid 1: sysexit end: io_setup(0x7fff1b22d8, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x7fff1b22d8 [0x7fff1b22d8, 0]
proot info: vpid 1: sysenter start: openat(0xffffffffffffff9c, 0x7fff1b2428, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffff9c [0x7fff1b22d8, 0]
proot info: vpid 1: translate("/" + "/bin/ash")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: sysenter end: openat(0xffffffffffffff9c, 0x7fff1b22b8, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffff9c [0x7fff1b22d8, 0]
proot info: vpid 1: sysenter start: openat(0xffffffffffffff9c, 0x7fff1b2431, 0x0, 0x0, 0x5, 0xd3000) = 0xffffffffffffff9c [0x7fff1b22d8, 0]
proot info: vpid 1: translate("/" + "/lib/ld-musl-aarch64.so.1")
proot info: vpid 1:          -> "/home/dextop/alpine/lib/ld-musl-aarch64.so.1"
proot info: vpid 1: sysenter end: openat(0xffffffffffffff9c, 0x7fff1b22ab, 0x0, 0x0, 0x5, 0xd3000) = 0xffffffffffffff9c [0x7fff1b22d8, 0]
proot info: vpid 1: translate("/" + "/bin/busybox")
proot info: vpid 1:          -> "/home/dextop/alpine/bin/busybox"
proot info: vpid 1: terminated with signal 7
```

**Comment by remexre** [comment] 2020-05-23 19:46
I'm getting same behavior on Manjaro on a Pinebook Pro (aarch64 as well). After building proot 5.2.0 alpha from source (modified installation instructions slightly by changing `make -C src loader.elf loader-m32.elf build.h` to `make -C src loader.elf build.h`):

```
$ mkdir ubuntu
$ curl http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04.6-base-arm64.tar.gz | tar -zx -C ubuntu --exclude 'dev/*'
$ proot -v 9 -b /home -S ubuntu
proot info: binding = /home/nathan/Desktop/ubuntu
proot info: binding = /home/nathan
proot info: binding = /tmp
proot info: binding = /proc
proot info: binding = /sys
proot info: binding = /dev
proot info: binding = /etc/resolv.conf
proot info: binding = /etc/nsswitch.conf
proot info: binding = /etc/hosts
proot info: binding = /etc/host.conf
proot info: binding = /home
proot info: binding = /home/nathan/Desktop/ubuntu:/
proot info: vpid 1: translate("/" + "/bin/sh")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/bin/dash"
proot info: vpid 1: translate("/" + "/bin/sh")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/bin/sh"
proot info: exe = /bin/sh
proot info: argv =
proot info: initial cwd = /home/nathan/Desktop
proot info: verbose level = 9
proot info: pid 88949: access to "/dev/pts/3" (fd 0) won't be translated until closed
proot info: pid 88949: access to "/proc/88949/fd" (fd 3) won't be translated until closed
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x98) = 0x26 [0xffffde87e6e0, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x98) = 0x26 [0xffffde87e6e0, 0]
proot info: vpid 1: sysexit start: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0x98) = 0x0 [0xffffde87e6e0, 0]
proot info: vpid 1: sysexit end: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0x98) = 0x0 [0xffffde87e6e0, 0]
proot info: vpid 1: sysenter start: execve(0xaaaadf4f8c80, 0xffffde87e7d8, 0xffffde87e9e8, 0x0, 0x40100401, 0xffff8f3ed6b8) = 0xaaaadf4f8c80 [0xffffde87e710, 0]
proot info: vpid 1: translate("/" + "/bin/sh")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/bin/dash"
proot info: vpid 1: translate("/" + "/lib/ld-linux-aarch64.so.1")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/lib/aarch64-linux-gnu/ld-2.23.so"
proot info: loader: /tmp/prooted-88949-HTbp56
proot info: vpid 1: sysenter end: execve(0xffffde87e6f6, 0xffffde87e7d8, 0xffffde87e9e8, 0x0, 0x40100401, 0xffff8f3ed6b8) = 0xffffde87e6f6 [0xffffde87e6f6, 0]
proot info: vpid 1: sysexit start: io_setup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0xffffde217fd0, 0]
proot info: vpid 1: sysexit end: io_setup(0xffffde217e58, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffffde217e58 [0xffffde217e58, 0]
proot info: vpid 1: sysenter start: openat(0xffffffffffffff9c, 0xffffde217fa8, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffff9c [0xffffde217e58, 0]
proot info: vpid 1: translate("/" + "/bin/sh")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/bin/dash"
proot info: vpid 1: sysenter end: openat(0xffffffffffffff9c, 0xffffde217e33, 0x0, 0x0, 0x0, 0x0) = 0xffffffffffffff9c [0xffffde217e58, 0]
proot info: vpid 1: sysenter start: openat(0xffffffffffffff9c, 0xffffde217fb0, 0x0, 0x0, 0xffffffffffffffff, 0x0) = 0xffffffffffffff9c [0xffffde217e58, 0]
proot info: vpid 1: translate("/" + "/lib/ld-linux-aarch64.so.1")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/lib/aarch64-linux-gnu/ld-2.23.so"
proot info: vpid 1: sysenter end: openat(0xffffffffffffff9c, 0xffffde217e1b, 0x0, 0x0, 0xffffffffffffffff, 0x0) = 0xffffffffffffff9c [0xffffde217e58, 0]
proot info: vpid 1: sysenter start: prctl(0xf, 0xffffde217fad, 0x0, 0x0, 0xffffde219297, 0x1c000) = 0xf [0xffffde217e58, 0]
proot info: vpid 1: sysenter end: prctl(0xf, 0xffffde217fad, 0x0, 0x0, 0xffffde219297, 0x1c000) = 0xf [0xffffde217e58, 0]
proot info: vpid 1: translate("/" + "/bin/dash")
proot info: vpid 1:          -> "/home/nathan/Desktop/ubuntu/bin/dash"
proot info: vpid 1: terminated with signal 7
```

**Comment by GTRI-nathan** [comment] 2020-09-15 21:20
Just a quick note - I had this too, and had to use the environment variable PROOT_NO_SECCOMP=1 to progress. (When trying to debug it in gdb, it printed out the warning message "It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161 To workaround it, set the env. variable PROOT_NO_SECCOMP to 1." I was using Centos7, so I guess I had an old kernel.

**Comment by nathanshearer** [comment] 2021-03-22 03:14
Running a static proot under a regular linux distribution appears to work fine. However, running proot under android always results in
`proot info: vpid 1: terminated with signal 7`

What can I do to work around this problem. There is no useful output explaining why proot is crashing or what I can do to try to fix the problem.

**Comment by oxr463** [comment] 2021-03-22 14:15
> Running a static proot under a regular linux distribution appears to work fine. However, running proot under android always results in
> `proot info: vpid 1: terminated with signal 7`
> 
> What can I do to work around this problem. There is no useful output explaining why proot is crashing or what I can do to try to fix the problem.

Perhaps you should try the Termux fork, https://github.com/termux/proot. It contains many Android-specific changes.

**Closed** 2021-09-07 22:19 UTC
Labels: kind/bug, kind/termux
